
import { jsPDF } from "jspdf";
import { BillingRecord } from "../types";

export const pdfService = {
  generateInvoice: async (record: BillingRecord, appName: string, currency: string) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // --- Header & Branding ---
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59); // Slate-900
    doc.text(appName.toUpperCase(), 20, 30);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text("SMART ENERGY BILLING SYSTEM", 20, 36);
    
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.line(20, 42, pageWidth - 20, 42);
    
    // --- Invoice Info ---
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE TO:", 20, 55);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text(record.occupantName, 20, 62);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`DATE: ${new Date(record.date).toLocaleDateString()}`, pageWidth - 20, 55, { align: "right" });
    doc.text(`REF ID: ${record.id.slice(0, 8).toUpperCase()}`, pageWidth - 20, 60, { align: "right" });
    
    // --- Billing Table ---
    let currentY = 80;
    
    // Table Header
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.rect(20, currentY, pageWidth - 40, 10, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(71, 85, 105); // Slate-600
    doc.text("DESCRIPTION", 25, currentY + 7);
    doc.text("DETAILS", 100, currentY + 7);
    doc.text("AMOUNT", pageWidth - 25, currentY + 7, { align: "right" });
    
    currentY += 15;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 41, 59);
    
    // Electricity Row
    const unitsText = record.isRentOnly ? "N/A" : `${record.previousUnit} - ${record.currentUnit} (${record.totalUnits} Units)`;
    doc.text("Electricity Consumption", 25, currentY);
    doc.text(unitsText, 100, currentY);
    const elecAmount = record.totalUnits * record.unitRate;
    doc.text(`${currency} ${elecAmount.toLocaleString()}`, pageWidth - 25, currentY, { align: "right" });
    
    currentY += 10;
    // Rent Row
    doc.text("Fixed Room Rent", 25, currentY);
    doc.text("-", 100, currentY);
    doc.text(`${currency} ${record.roomRent.toLocaleString()}`, pageWidth - 25, currentY, { align: "right" });
    
    currentY += 10;
    // Arrears Row
    doc.text("Previous Balance / Arrears", 25, currentY);
    doc.text("-", 100, currentY);
    doc.text(`${currency} ${record.previousBalance.toLocaleString()}`, pageWidth - 25, currentY, { align: "right" });
    
    currentY += 15;
    doc.setDrawColor(241, 245, 249);
    doc.line(20, currentY - 5, pageWidth - 20, currentY - 5);
    
    // --- Total ---
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("TOTAL DUE:", 100, currentY + 5);
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.text(`${currency} ${record.totalAmount.toLocaleString()}`, pageWidth - 25, currentY + 5, { align: "right" });
    
    // --- Footer ---
    const footerY = doc.internal.pageSize.getHeight() - 30;
    doc.setDrawColor(226, 232, 240);
    doc.line(20, footerY, pageWidth - 20, footerY);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(`Generated by ${appName} Billing Engine. This is a computer-generated document.`, pageWidth / 2, footerY + 10, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.text("Thank you for your timely payment!", pageWidth / 2, footerY + 15, { align: "center" });
    
    doc.save(`${record.occupantName}_Bill_${new Date(record.date).toISOString().slice(0,10)}.pdf`);
  }
};
